name: MacOS (clang)
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:
jobs:
  tests:
    runs-on: macOS-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v2
      - name: Aquire dependencies and compile
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          brew install llvm@16
          export PATH="/opt/homebrew/opt/llvm@16/bin:$PATH"
          export LDFLAGS="-L/opt/homebrew/opt/llvm@16/lib"
          export CPPFLAGS="-I/opt/homebrew/opt/llvm@16/include"
          clang --version
          make CC=clang
      - name: Run test script
        shell: bash
        run: |
          cd $GITHUB_WORKSPACE
          export PATH="/opt/homebrew/opt/llvm@16/bin:$PATH"
          export LDFLAGS="-L/opt/homebrew/opt/llvm@16/lib"
          export CPPFLAGS="-I/opt/homebrew/opt/llvm@16/include"
          clang --version
          make test -j8
      - name: Upload test output
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: tests-macOS-clang
          path: tests/*.*
